In [170]:
import pandas as pd
import numpy as np

In [171]:
#we have this list
#.1 what data structure is 
#2. how can we access to a specific element
mat = [[1,2, 3, 4,5],
       [5, 6, 7, 8, 9],
       [10, 11, 12, 13, 14]]
type(mat)

#so in programming this list is type of List on python software that contains items like numbers or characters that ordered and changeable and allow duplicates
#in math it contains 3 rown and 5 columns as it's below
index=np.array(mat) # casting
index.shape
# to access an element 
mat[2][1] # first [] it's about the position of row and second [] is for element


11

In [172]:
import math

In [173]:
# to return sin/cos/factorial
#using sin, means we will need to use radians to return sin X number
math.sin(math.radians(20))

math.cos(23)

math.factorial(23)

#the mathematical constant  pi it returns 3.141592653589793 and it's ratio
#of circle's circumference to its diameter
math.pi 
help(math.degrees)



Help on built-in function degrees in module math:

degrees(x, /)
    Convert angle x from radians to degrees.



In [174]:
##The Object SpA has created a list of quanti-oggetti that has been made 
# available:
##respond to all the CEO della Object SpA: 
# • What is the max status of monthly sale, and minimum ?
# what are the monthly sales more than 5000 items and how many are they?
#and what are the lower than 3000?
# as average how many items have been sold out in month

lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]
array_lst=np.array(lst)

array_lst.max()
array_lst.min() 

#to filter >5000
array_lst[array_lst>5000]
#or
filter= array_lst>5000
f=array_lst[filter]
print(f)

#to count the filter items 
(array_lst>5000).sum()
#or 
#data500=array_lst[array_lst>5000]
#print(len(data500))

#lower than 3000
array_lst[array_lst<3000]
#|
filter2=array_lst<3000
print(array_lst[filter2])


#the monthly average 
array_lst.mean()






[5500 7200 6410 8150 7100 5350]
[2000 1280 1900 2500]


4634.166666666667

In [175]:
fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000,
                 2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000}
fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 
                            17_000, 14_000, 21_000], 
                            index=range(1997, 2005)) 
fatturati_dict[1997] # this is a dict built-in function , it stocks items with easy access through key items
fatturati_series[1997]# this is a type of numpy/pandas.series, which like array. access is through tickets/labels 

#things we can do with series not possibile with dict --> statistic operations
fatturati_series.mean()
fatturati_series.max()
fatturati_series.min()
fatturati_series.std()# devision 

4596.194077712559

In [176]:
# using numpy for this array of saleries 

saleries=np.array([100, 200, 300, 400, 500, 600, 700, 800, 900, 1000])# casting

#mutiplication*2
for salery in saleries:
    print(salery*2)
#or 
saleries*2

200
400
600
800
1000
1200
1400
1600
1800
2000


array([ 200,  400,  600,  800, 1000, 1200, 1400, 1600, 1800, 2000])

In [177]:
# ex pag 8 to check
series=[10,500,300,40,40,5,700,810,810,10,12,700]
#create set to have no duplicates and then we will use sort to order it
new_series =set(series)
print(new_series)
#but here we need list connected to set to 
#avoid duplicates 
nnew_series=list(set(series))
print(nnew_series)
# to have the 3 largest N
nnew_series.sort()# in that case it's normal order and from smaller to bigger 
nnew_series[0:3]
nnew_series.sort(reverse=True)
nnew_series[0:3]



{5, 40, 10, 810, 300, 12, 500, 700}
[5, 40, 10, 810, 300, 12, 500, 700]


[810, 700, 500]

In [178]:
numbers = [5, 2, 3, 4]
star=('*')
for number in numbers:
    print(star*number)
#or 
#numbers = [5, 2, 3, 4]
#for number in numbers:
    #print('*' * number)

*****
**
***
****


In [179]:
program= np.array( [30,10,20,100,200,500,150])
k=100

filter=program>k
datak=program[filter]

if len(datak)== 0 :
    print ('there is not  items')
else:
    print('there are items and average :', round(datak.mean()))

there are items and average : 283


In [ ]:
lista_cf = ["ABCDEF95G01A123B", "GHIJKL91M02A321C",
             "MNOPQR89S03A456D", "STUVWX95Z04A654E",
                "XYZABC01D05A789F", "DEFGHI95J06A987G"]

for cf in lista_cf:
    if '95' in cf:
        print (cf)
for cf in lista_cf:
    second_name=cf [0:3]
    first_name=cf[3:6]
    print('code :',cf ,'first name:',first_name , 'second name',second_name)

# or 

#cf_list=[]
#for cf in lista_cf:
    #if '95' in cf:
        #print(cf,'first name:',cf[0:3],'second_name :', cf[3:6])
        #cf_list.append(cf)
#print(cf_list)



ABCDEF95G01A123B
STUVWX95Z04A654E
DEFGHI95J06A987G
code : ABCDEF95G01A123B first name: DEF second name ABC
code : GHIJKL91M02A321C first name: JKL second name GHI
code : MNOPQR89S03A456D first name: PQR second name MNO
code : STUVWX95Z04A654E first name: VWX second name STU
code : XYZABC01D05A789F first name: ABC second name XYZ
code : DEFGHI95J06A987G first name: GHI second name DEF


In [197]:
studenti = ["Alex", "Bob", "Cindy", "Dan", "Emma", "Faith", "Grace", "Henry"]
corsi = ["Cybersecurity", "Data Analyst", "Backend", "Frontend", "Data Analyst", 
         "Backend", "Frontend", "Cybersecurity"]
edizioni = [1, 2, 3, 2, 2, 1, 3, 3]

for student in range(len(studenti)):
    if edizioni[student]==1 :
        print(studenti[student])
 
#or
st=pd.Series(studenti,index=edizioni)# note if you have already the list, so write it without braces
print(st[1])

#or
for edition in range(len(edizioni)):
     ED=edizioni[edition]
     if ED ==1:
       print(studenti[edition])

Alex
Faith
1     Alex
1    Faith
dtype: object
Alex
Faith


In [183]:
price = ["100 €", "200 €", "500 €", "10 €", "50 €", "70 €"]
#to change  € in $ 

dollar=[p.replace('€','$') for p in price]
print(dollar)

['100 $', '200 $', '500 $', '10 $', '50 $', '70 $']


In [184]:
#to check
students = ["Alex", "Bob", "Cindy", "Dan", "Emma", "Faith", 
            "Grace", "Henry", "Isabelle", "John"]
# even names
stu= [students[student] for student in range(len(students)) if student%2==0]
 
print (stu)

stu2= [students[student] for student in range(len(students)) if student%2!=0]

print (stu2)

['Alex', 'Cindy', 'Emma', 'Grace', 'Isabelle']
['Bob', 'Dan', 'Faith', 'Henry', 'John']


In [185]:
earnings = [100, 90, 70, 40, 50, 80, 90, 120, 80, 20, 50, 50]
for earning in range(len(earnings)):
    month=1+earning
    recent_earning=earnings[earning] 